const GameState = {
  INTRO: "INTRO",
  STORY: "STORY",
  LOGIN: "LOGIN",
  MAIN_PAGE: "MAIN_PAGE",

  WTG: "WTG",
  BESS: "BESS",
  SOLAR: "SOLAR",
  SUBSTATION: "SUBSTATION",

  ASSET_INVENTORY: "ASSET_INVENTORY",
  PATCH_MGMT: "PATCH_MGMT",
  ACCESS_MGMT: "ACCESS_MGMT",
  BCM_DR: "BCM_DR"
};